export const COMENZAR_REGISTRO_USUARIO = 'COMENZAR_REGISTRO_USUARIO'
export const REGISTRAR_USUARIO_EXITO = 'REGISTRAR_USUARIO_EXITO'
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR'

export const COMENZAR_LOGIN_USUARIO = 'COMENZAR_LOGIN_USUARIO'
export const LOGIN_USUARIO_EXITO = 'LOGIN_USUARIO_EXITO'
export const LOGIN_USUARIO_ERROR = 'LOGIN_USUARIO_ERROR'

export const LOGOUT_USUARIO = 'LOGOUT_USUARIO'